language: python3
fuzzing_engines:
  - libfuzzer
sanitizers: #я не уверен, что тут вообще должен быть этот раздел, ведь питон это интерпритируемиый язык, а не компилируемый (то есть он не компилируется с санитайзерами...)
  - address 
  - undefined
