homepage: "https://github.com/lenix123/django_fuzz"
main_repo: "https://github.com/django/django"
language: python
primary_contact: "a.zarudnyi@fobos-nt.ru"
auto_ccs:
  - "pixel133701@gmail.com"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined